name: 👾 Bug Report 
descrption: Report a bug.
title: ""
labels: ["Bug"]
assignees: ["PortetWilfried"]
body:
  - type: markdown
  attributes:
  value: |
    Please fill out the sections below to help the team to fix the bug.
  - type: textarea
    id: description
    attributes:
      label: Describe your issue 
      placeholder: Please describe the problem ?
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      placeholder: The date in "dd/mm/yyyy"
  - type: textarea
    id: Path
    attributes:
      label: Steps to reproduce
      placeholder: 
      1. Go to X 
      2. click here
      3. click there
  - type: textarea
    id: changes
    attributes:
      label: What was the expected result ?
      placeholder: I expected X to happen
    validations:
      required: true 
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      options:
        - 1 - Urgent 🚨
        - 2 - High Priority ❗
        - 3 - Normal Priority 🆗
        - 4 - Low Priority 😎
        - 5 - Informational 🛈
    validations:
      required: true 
  - type: checkboxes
    id: terms
    attributes:
    label: Extra Field
    options:
      - I want to work on this issue
  - type: markdown 
    attributes:
      value : |
        Thanks for reporting this issue ! The team will try to solve the problem.

        